SupportAplikacija/Controllers/RacunarController.cs
using DAL;
using DAL.Models;
using DAL.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SupportAplikacija.Controllers
{
    [Authorize]
    public class RacunarController : Controller
    {
        SupportContext context = new SupportContext();
        // GET: Racunar
        public ActionResult Index(string searchInput = "", string sistemSelect = "", string processorSelect = "", int itemsPerPage = 25, int currentPage = 0, int klijentId = 0)
        {
            try
            {
                    List<RacunarVM> racunari = context.Racunar.Select(x => new RacunarVM
                    {
                        RacunarId = x.RacunarId,
                        KlijentId = x.KlijentId,
                        Klijent = x.Klijent.Ime + "-" + x.Klijent.Alias,
                        OperativniSistemId = x.OperativniSistem.OperativniSistemId,
                        OperativniSistem = x.OperativniSistem.Name,
                        ProcesorId = x.Procesor.ProcesorId,
                        Procesor = x.Procesor.Name,
                        TipRacunara = x.TipRacunara.Name,
                        RAM = x.RAM,
                        Graficka = x.Graficka.Name,
                        VrstaMemorije = x.VrstaMemorije.Name,
                        KolicinaMemorije = x.KolicinaMemorije

                    }).Where(x => (klijentId != 0 ? x.KlijentId == klijentId : true))
                      .OrderByDescending(x => x.Klijent)
                      .ToList();

                    ViewBag.ListaSistema = context.OperativniSistem.ToList();
                    ViewBag.ListaProcesora = context.Procesor.ToList();

                    if (searchInput != "")
                    {
                        racunari = racunari.Where(x => x.Klijent.Contains(searchInput)).ToList();
                    }

                    if (sistemSelect != "")
                    {
                        racunari = racunari.Where(x => x.OperativniSistemId.ToString().Equals(sistemSelect)).ToList();
                    }

                    if (processorSelect != "")
                    {
                        racunari = racunari.Where(x => x.ProcesorId.ToString().Equals(processorSelect)).ToList();
                    }

                    if (klijentId != 0)
                    {
                        ViewBag.klijentId = klijentId;

                        return PartialView("Index_Partial", racunari);
                    }

                    //pagging calculations (number of pages)
                    decimal numberOfPages = (decimal)racunari.Count / (decimal)itemsPerPage;
                    ViewBag.numberOfPages = Math.Ceiling(numberOfPages);

                    //set current page to make it visible on the html
                    ViewBag.currentPage = currentPage;

                    //pagging calculations (skip and take elements)
                    racunari = racunari.Skip(currentPage * itemsPerPage).Take(itemsPerPage).ToList();

                    ViewBag.selectedSistem = sistemSelect;
                    ViewBag.selectedProcessor = processorSelect;
                    ViewBag.searchInput = searchInput;
                    Session["Selected"] = "RacunarIndex";

                    return View(racunari);
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        // GET: Racunar/Details/5
        public ActionResult Details(int id, int klijentId = 0)
        {
            try
            {
                    RacunarVM racunarVM = context.Racunar.Where(x => x.RacunarId == id).Select(x => new RacunarVM
                    {
                        RacunarId = x.RacunarId,
                        Procesor = x.Procesor.Name,
                        OperativniSistem = x.OperativniSistem.Name,
                        KlijentId = x.KlijentId,
                        Klijent = x.Klijent.Ime + "-" + x.Klijent.Alias,
                        RAM = x.RAM,
                        KolicinaMemorije = x.KolicinaMemorije,
                        TipRacunara = x.TipRacunara.Name,
                        VrstaMemorije = x.VrstaMemorije.Name,
                        Graficka = x.Graficka.Name
                    }).FirstOrDefault();

                    if (klijentId != 0)
                    {
                        return PartialView("Details_Partial", racunarVM);
                    }

                    return View(racunarVM);
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        // GET: Racunar/Create
        public ActionResult Create(int id = 0, int klijentId = 0)
        {
            try
            {
                RacunaCreateVM racunarVM = new RacunaCreateVM();
                    InitializeDropdowns(racunarVM);

                    if (id != 0)
                    {
                        Racunar racunar = context.Racunar.Where(x => x.RacunarId == id).FirstOrDefault();
                        racunarVM.KlijentId = racunar.KlijentId;
                        racunarVM.RacunarId = id;
                        racunarVM.OperativniSistemId = racunar.OperativniSistemId;
                        racunarVM.ProcesorId = racunar.ProcesorId;
                        racunarVM.TipRacunaraId = racunar.TipRacunaraId;
                        racunarVM.RAM = racunar.RAM;
                        racunarVM.GrafickaId = racunar.GrafickaId;
                        racunarVM.VrstaMemorijeId = racunar.VrstaMemorijeId;
                        racunarVM.KolicinaMemorije = racunar.KolicinaMemorije;
                    }

                    if (klijentId != 0)
                    {
                        racunarVM.KlijentId = klijentId;
                        racunarVM.IsPartial = true;

                        ViewBag.allErrors = null;
                        return PartialView("Create_Partial", racunarVM);
                    }

                    racunarVM.Klijenti = context.Klijent.Select(x => new SelectListItem
                    {
                        Text = x.Ime,
                        Value = x.KlijentId.ToString()
                    }).ToList();

                    return View(racunarVM);
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        // POST: Racunar/Create
        [HttpPost]
        public ActionResult Create(RacunaCreateVM racunarVM)
        {
            try
            {
                Racunar racunar;

                    if (racunarVM.RacunarId == 0)
                    {
                        //Kreira novu intervenciju i odma je posprema u bazu 
                        racunar = new Racunar();
                        context.Racunar.Add(racunar);
                    }
                    else
                    {
                        //Vadi postojecu intervenciju za editovanje 
                        racunar = context.Racunar.Where(x => x.RacunarId == racunarVM.RacunarId).FirstOrDefault();
                    }

                    #region Provjera da li je sve ispravno uneseno

                    List<string> allErrors = new List<string>();

                    if (!ModelState.IsValid)
                    {
                        Response.AppendHeader("X-Error", "true");

                        foreach (ModelState modelState in ViewData.ModelState.Values)
                        {
                            foreach (ModelError error in modelState.Errors)
                            {
                                allErrors.Add(error.ErrorMessage.ToString());
                            }
                        }

                        InitializeDropdowns(racunarVM);
                        
                        if (racunarVM.IsPartial)
                        {
                            ViewBag.allErrors = allErrors;
                            return PartialView("Create_Partial", racunarVM);
                        }

                        return Json(allErrors);
                    }
    
                    #endregion

                    racunar.OperativniSistemId = racunarVM.OperativniSistemId;
                    racunar.TipRacunaraId = racunarVM.TipRacunaraId;
                    racunar.ProcesorId = racunarVM.ProcesorId;
                    racunar.KlijentId = racunarVM.KlijentId;
                    racunar.RAM = racunarVM.RAM;
                    racunar.GrafickaId = racunarVM.GrafickaId;
                    racunar.VrstaMemorijeId = racunarVM.VrstaMemorijeId;
                    racunar.KolicinaMemorije = racunarVM.KolicinaMemorije;

                    context.SaveChanges();

                    if (racunarVM.IsPartial)
                        return Redirect("/Racunar/Index?klijentId=" + racunarVM.KlijentId);

                    return Redirect("/Racunar/Index");
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        // POST: Racunar/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, int klijentId = 0)
        {
            try
            {
                    context.Racunar.Remove(context.Racunar.Where(x => x.RacunarId == id).FirstOrDefault());
                    context.SaveChanges();

                    if (klijentId != 0)
                        return Redirect("/Racunar/Index?klijentId=" + klijentId);

                    return RedirectToAction("Index");
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

SupportAplikacija/Views/Racunar/Details_Partial.cshtml
@model DAL.ViewModel.RacunarVM

<link href="~/vendor/bootstrap/css/table-style.min.css" rel="stylesheet" />
<link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/vendor/bootstrap/css/simple-sidebar.min.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open Sans">

<div id="detailsCard" class="card" style="width:100%;">
    <div class="card-block" style="margin:2% 2% 0 0;">
        <a class="btn editBtn pull-right" href='#' title="Izbriši" style="font-size:15px;" onclick="deleteRacunar(@Model.RacunarId,@Model.KlijentId)"><i class="fa fa-trash fa-wa" style="color:#696666;"></i></a>
        <a class="btn editBtn pull-right" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#ajaxDiv" href='@Url.Action("Create", "Racunar", new {id = Model.RacunarId,klijentId = Model.KlijentId})' title="Uredi" style="font-size:15px;"><i class="fa fa-pencil fa-wa" style="color:#696666;"></i></a>
    </div>
    <div class="card-block card-body text-center">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <td style="width:50%;" class="align-content-right"><strong>Tip Računara:</strong></td>
                    <td style="width:50%;" class="align-content-left">@Html.DisplayFor(x => x.TipRacunara)</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>Procesor:</strong></td>
                    <td class="align-content-left">@Html.DisplayFor(x => x.Procesor)</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>Operativni Sistem:</strong></td>
                    <td class="align-content-left">@Html.DisplayFor(x => x.OperativniSistem)</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>RAM:</strong></td>
                    <td class="align-content-left">@Html.DisplayFor(x => x.RAM)</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>Vrsta Memorije:</strong></td>
                    <td class="align-content-left">@Html.DisplayFor(x => x.VrstaMemorije)</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>Količina Memorije:</strong></td>
                    <td class="align-content-left">@Html.DisplayFor(x => x.KolicinaMemorije)</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>Grafička:</strong></td>
                    <td class="align-content-left">@Html.DisplayFor(x => x.Graficka)</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    function deleteRacunar(racunarId,klijentId) {
        swal({
            title: 'Dali ste sigurni?',
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Da, obriši!',
            cancelButtonText: 'Ne',
        }).then((result) => {
            if (result.value) {
            	$.ajax({
                    type: "POST",
                    url: "/Racunar/Delete?id=" + racunarId + "&klijentId=" + klijentId,
                    success:function(response){$("#ajaxDiv").html(response);},
                });
            }
        })
    }
</script>

SupportAplikacija/Views/Racunar/Index.cshtml
@model IEnumerable<DAL.ViewModel.RacunarVM>
@using DAL.Models;

@{
    ViewBag.Title = "Računari";
    var numberOfPages = (int)ViewBag.numberOfPages;
    var currentPage = (int)ViewBag.currentPage;

    //filteri
    var searchInput = (string)ViewBag.searchInput;
    var selectedSistem = (string)ViewBag.selectedSistem;
    var selectedProcessor = (string)ViewBag.selectedProcessor;
    var listOfSistems = (List<OperativniSistem>)ViewBag.ListaSistema;
    var listOfProcessors = (List<Procesor>)ViewBag.ListaProcesora;

    //fatal error
    var fatalError = (string)ViewBag.fatalError;
}

@if (fatalError != null)
{
    <div class="alert alert-danger">
        @fatalError.ToString()
    </div>
}
<div class="container-style">
    @*filteri za pretragu klijenata i dugme za dodavanje novog klijenta*@
    <div id="filterWrapper">
        <form action="/Racunar/Index" method="get" class="form-inline">
            <a href="" data-toggle="modal" data-target="#infoModal" class="mr-1" title="Informacije o pretrazi..."><i class="fa fa-info-circle icon-size" aria-hidden="true" style="color:#168ece"></i></a>
            <input id="searchInput" type="text" name="searchInput" class="form-control mb-2 mr-sm-2 mb-sm-0" placeholder="Pretraga..." value="@searchInput" />

            <select id="sistemSelect" name="sistemSelect" class="form-control mb-2 mr-sm-2 mb-sm-0">
                <option @(selectedSistem == "" ? "selected" : "") value="">Operativni sistem</option>
                @foreach (var item in listOfSistems)
                {
                    <option @(selectedSistem == item.OperativniSistemId.ToString() ? "selected" : "") value="@item.OperativniSistemId">@item.Name</option>
                }
            </select>

            <select id="processorSelect" name="processorSelect" class="form-control mb-2 mr-sm-2 mb-sm-0">
                <option @(selectedProcessor == "" ? "selected" : "") value="">Procesor</option>
                @foreach (var item in listOfProcessors)
                {
                    <option @(selectedProcessor == item.ProcesorId.ToString() ? "selected" : "") value="@item.ProcesorId">@item.Name</option>
                }
            </select>

            <button id="searchBtn" type="submit" class="btn createBtn form-control mb-2 mr-sm-2 mb-sm-0 pointer">Pretraži&nbsp;<i class="fa fa-search fa-fw"></i></button>

            <a id="clearFilterBtn" href="/Racunar/Index" class="btn btn-danger form-control mb-2 mr-sm-2 mb-sm-0 pointer">Očisti filtere&nbsp;<i class="fa fa-times fa-fw"></i></a>
        </form>
    </div>

    <div style="margin-bottom:2%;">
        @Html.ActionLink("Dodaj Računar", "Create", null, new { @class = "btn btn-info" })
    </div>
    @*tabela sa listom klijenata*@
    @if (Model.Count() > 0)
    {
        <table id="racunarTable" class="table">
            <thead>
                <tr>
                    <th scope="col" style="width:10%;">Klijent</th>
                    <th scope="col" style="width:10%;">Tip Računara</th>
                    <th scope="col" style="width:5%;">Procesor</th>
                    <th scope="col" style="width:10%;">Operativni Sistem</th>
                    <th scope="col" style="width:5%;">RAM</th>
                    <th scope="col" style="width:10%;">Grafička</th>
                    <th scope="col" style="width:10%;">Vrsta Memorije</th>
                    <th scope="col" style="width:10%;">Količina Memorije</th>
                    <th scope="col" style="text-align:center; width:10%;"></th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr style="background: rgba(164, 209, 234, 0.1); ">
                    <td scope="row" data-label="Klijent">@Html.DisplayFor(modelItem => item.Klijent)</td>
                    <td data-label="Tip Računara">@Html.DisplayFor(modelItem => item.TipRacunara)</td>
                    <td data-label="Procesor">@Html.DisplayFor(modelItem => item.Procesor)</td>
                    <td data-label="Operativni Sistem">@Html.DisplayFor(modelItem => item.OperativniSistem)</td>
                    <td data-label="RAM">@Html.DisplayFor(modelItem => item.RAM)</td>
                    <td data-label="Grafička">@Html.DisplayFor(modelItem => item.Graficka)</td>
                    <td data-label="Vrsta Memorije">@Html.DisplayFor(modelItem => item.VrstaMemorije)</td>
                    <td data-label="Količina Memorije">@Html.DisplayFor(modelItem => item.KolicinaMemorije)</td>
                    <td style="text-align:right;">
                        <a class="btn editBtn" href='@Url.Action("Create", "Racunar", new {id = item.RacunarId, klijentId = 0})' title="Uredi"><i class="fa fa-pencil fa-wa" style="color:#696666;"></i></a>
                        <a class="btn editBtn" href='#' title="Izbriši" onclick="deleteRacunar(@item.RacunarId)"><i class="fa fa-trash fa-wa" style="color:#696666;"></i></a>
                    </td>
                </tr>
            }
        </table>
    }
    else
    {
        <div class="alert" style="text-align:center; background-color:rgba(175,175,175,0.1);">
            <h5>Nije pronađen nijedan računar</h5>
        </div>
    }

    @*paginacija*@
    @if (numberOfPages > 1)
    {
        <div class="container">
            <ul class="pagination pagging-alignment">
                <li class="page-item  @(currentPage == 0?"disabled":"") "><a class="page-link" href="/Racunar/Index?currentPage=@(currentPage-1)">Prethodni</a></li>

                @for (int i = 0; i < numberOfPages; i++)
                {
                    <li class="page-item @(currentPage == i?" active":"")"><a class="page-link" href="/Racunar/Index?currentPage=@i">@(i + 1)</a></li>
                }

                <li class="page-item @(currentPage == numberOfPages-1?"disabled":"")"><a class="page-link" href="/Racunar/Index?currentPage=@(currentPage+1)">Sljedeći</a></li>
            </ul>
        </div>
    }
</div>

<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                Pretraga se može vršiti po sljedećem parametru:
                <ul>
                    <li>Klijent</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function deleteRacunar(racunarId) {
        swal({
            title: 'Dali ste sigurni?',
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Da, obriši!',
            cancelButtonText: 'Ne',
        }).then((result) => {
            if (result.value) {
                $.ajax({
            type: "POST",
            url: "/Racunar/Delete?id=" + racunarId + "&klijentId=0",
        success: (location.href = "/Racunar/Index"),
        dataType: "json"
    });
    }
    })
    }
</script>

SupportAplikacija/Views/Racunar/Index_Partial.cshtml
@model IEnumerable<DAL.ViewModel.RacunarVM>

@{
    int klijentId = (int)ViewBag.klijentId;
}

<link href="~/vendor/bootstrap/css/table-style.min.css" rel="stylesheet" />
<link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/vendor/bootstrap/css/simple-sidebar.min.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open Sans">

<p>
    @Ajax.ActionLink("Dodaj novi računar", "Create", new { klijentId = klijentId }, new AjaxOptions { UpdateTargetId = "ajaxDiv" }, new { @class = "btn btn-info" })
</p>

@if (Model.Count() > 0)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" style="width:10%;">Tip Računara</th>
                <th scope="col" style="width:10%;">Procesor</th>
                <th scope="col" style="width:10%;">Operativni Sistem</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr class="click" style="background: rgba(164, 209, 234, 0.1); " data-href="/Racunar/Details/@item.RacunarId?klijentId=@item.KlijentId" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#ajaxDiv">
                <td data-label="Tip Računara">@Html.DisplayFor(modelItem => item.TipRacunara)</td>
                <td data-label="Procesor">@Html.DisplayFor(modelItem => item.Procesor)</td>
                <td data-label="Operativni Sistem">@Html.DisplayFor(modelItem => item.OperativniSistem)</td>
            </tr>
        }
    </table>
}
else
{
    <div class="alert" style="text-align:center; background-color:rgba(175,175,175,0.1);">
        <h5>Nije pronađen nijedan računar</h5>
    </div>
}

<script>
    $(".click").click(function () {
        $.ajax({

            type: "GET",
            url: $(this).data("href"),
            success: function (data) {
                // data is ur summary
                $('#ajaxDiv').html(data);
            }
        });
    })
</script>