SupportAplikacija/Controllers/KlijentController.cs
using DAL;
using DAL.Models;
using DAL.ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SupportAplikacija.Controllers
{
    [Authorize]
    public class KlijentController : Controller
    {
        SupportContext context = new SupportContext();

        // GET: /Klijent/
        public ActionResult Index(string searchInput = "", string dateFrom = "", string dateTo = "", int itemsPerPage = 25, int currentPage = 0)
        {
            try
            {
                List<KlijentVM> klijenti = context.Klijent.Select(x => new KlijentVM
                {
                    KlijentId = x.KlijentId,
                    Ime = x.Ime,
                    Alias = x.Alias,
                    Adresa = x.Adresa,
                    DatumDodavanja = x.DatumDodavanja,
                    Telefon = x.Telefon,
                    Grad = x.Grad.Naziv,
                    DatumUredjivanja = x.DatumUredjivanja
                }).OrderByDescending(x => x.DatumDodavanja)
                  .ToList();

                if (searchInput != "")
                {
                    klijenti = klijenti.Where(x => x.Ime.Contains(searchInput) ||
                                              x.Alias.Contains(searchInput) ||
                                              x.Telefon.Contains(searchInput) ||
                                              x.Grad.Contains(searchInput) ||
                                              x.Adresa.Contains(searchInput)).ToList();
                }

                if (dateFrom != "")
                {
                    klijenti = klijenti.Where(x => x.DatumDodavanja.Date >= DateTime.Parse(dateFrom).Date).ToList();
                }

                if (dateTo != "")
                {
                    klijenti = klijenti.Where(x => x.DatumDodavanja.Date <= DateTime.Parse(dateTo).Date).ToList();
                }

                //pagging calculations (number of pages)
                decimal numberOfPages = (decimal)klijenti.Count / (decimal)itemsPerPage;
                ViewBag.numberOfPages = Math.Ceiling(numberOfPages);

                //set current page to make it visible on the html
                ViewBag.currentPage = currentPage;

                //pagging calculations (skip and take elements)
                klijenti = klijenti.Skip(currentPage * itemsPerPage).Take(itemsPerPage).ToList();

                //spašavanje trenutnih vrijednosti filtera kako se nebi obrisali nakon pretrage
                ViewBag.searchInput = searchInput;
                ViewBag.dateFrom = dateFrom;
                ViewBag.dateTo = dateTo;
                Session["Selected"] = "KlijentIndex";

                return View(klijenti);
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        //
        // GET: /Klijent/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                KlijentVM klijent = context.Klijent.Select(x => new KlijentVM
                {
                    KlijentId = x.KlijentId,
                    Ime = x.Ime,
                    Alias = x.Alias,
                    Telefon = x.Telefon,
                    Grad = x.Grad.Naziv,
                    Adresa = x.Adresa,
                    DatumDodavanja = x.DatumDodavanja,
                    DatumUredjivanja = x.DatumUredjivanja,
                    Napomena = x.Napomena
                }).Where(x => x.KlijentId == id).FirstOrDefault();

                return View(klijent);
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        //
        // GET: /Klijent/Create
        public ActionResult Create(int id = 0, string error = null)
        {
            try
            {
                ViewBag.error = error;

                KlijentCreateVM klijentVM = new KlijentCreateVM()
                {
                    Gradovi = context.Grad.Select(x => new SelectListItem
                    {
                        Text = x.Naziv,
                        Value = x.GradId.ToString()
                    }).ToList()
                };

                if (id != 0)
                {
                    Klijent klijent = context.Klijent.Where(x => x.KlijentId == id).FirstOrDefault();
                    klijentVM.Adresa = klijent.Adresa;
                    klijentVM.Ime = klijent.Ime;
                    klijentVM.Alias = klijent.Alias;
                    klijentVM.Telefon = klijent.Telefon;
                    klijentVM.GradId = klijent.GradId;
                    klijentVM.KlijentId = klijent.KlijentId;
                    klijentVM.Napomena = klijent.Napomena;
                }

                return View(klijentVM);
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        //
        // POST: /Klijent/Create
        [HttpPost]
        public ActionResult Create(KlijentCreateVM klijentVM)
        {
            try
            {
                List<string> allErrors = new List<string>();
                Klijent klijent = context.Klijent.Where(x => x.Ime.Equals(klijentVM.Ime) &&
                                                             x.Alias.Equals(klijentVM.Alias) &&
                                                             x.Napomena.Equals(klijentVM.Napomena) &&
                                                             x.Telefon.Equals(klijentVM.Telefon) &&
                                                             x.Adresa.Equals(klijentVM.Adresa) &&
                                                             x.GradId == klijentVM.GradId).FirstOrDefault();

                if (klijent != null)
                {
                    Response.AppendHeader("X-Error", "true");
                    allErrors.Add("Klijent već postoji!");
                    return Json(allErrors);
                }

                if (klijentVM.KlijentId == 0)
                {

                    //Kreira novog klijenta i odma ga posprema u bazu 
                    klijent = new Klijent();
                    klijent.DatumDodavanja = DateTime.Now;
                    klijent.DatumUredjivanja = DateTime.Now;
                    context.Klijent.Add(klijent);
                }
                else
                {
                    //Vadi postojeceg klijenta za editovanje 
                    klijent = context.Klijent.Where(x => x.KlijentId == klijentVM.KlijentId).FirstOrDefault();
                    klijent.DatumUredjivanja = DateTime.Now;
                }

                #region Provjera da li je sve ispravno uneseno
                if (!ModelState.IsValid)
                {
                    klijentVM.Gradovi = context.Grad.Select(x => new SelectListItem
                    {
                        Text = x.Naziv,
                        Value = x.GradId.ToString()
                    }).ToList();

                    Response.AppendHeader("X-Error", "true");

                    foreach (ModelState modelState in ViewData.ModelState.Values)
                    {
                        foreach (ModelError error in modelState.Errors)
                        {
                            allErrors.Add(error.ErrorMessage.ToString());
                        }
                    }

                    return Json(allErrors);
                }
                #endregion

                klijent.Ime = klijentVM.Ime;
                klijent.Alias = klijentVM.Alias;
                klijent.GradId = klijentVM.GradId;
                klijent.Telefon = klijentVM.Telefon;
                klijent.Adresa = klijentVM.Adresa;
                klijent.Napomena = klijentVM.Napomena;

                context.SaveChanges();

                return Redirect("/Klijent/Index");
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        //
        // GET: /Klijent/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                context.Klijent.Remove(context.Klijent.Where(x => x.KlijentId == id).SingleOrDefault());
                context.SaveChanges();
                return Redirect("/Klijent/Index");
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        [HttpGet]
        public ActionResult CreateGrad()
        {
            try
            {
                GradCreateVM gradVM = new GradCreateVM();

                return PartialView("CreateGrad_Partial", gradVM);
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        [HttpPost]
        public ActionResult CreateGrad(GradCreateVM gradVM)
        {
            try
            {
                List<string> allErrors = new List<string>();
                Grad grad = context.Grad.Where(x => x.Naziv.Equals(gradVM.Naziv.Trim())).FirstOrDefault();

                if (grad != null)
                {
                    Response.AppendHeader("X-Error", "true");
                    allErrors.Add("Grad već postoji!");
                    return Json(allErrors);
                }

                if (gradVM.Naziv == String.Empty)
                {
                    Response.AppendHeader("X-Error", "true");
                    allErrors.Add("Naziv ne može biti prazan!");

SupportAplikacija/Controllers/SlikaController.cs
using DAL;
using DAL.Models;
using DAL.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace SupportAplikacija.Controllers
{
    [Authorize]
    public class SlikaController : Controller
    {
        SupportContext context = new SupportContext();

        // GET: Slika
        public ActionResult Index(int klijentId)
        {
            try
            {
                    List<SlikaVM> slike = context.Slika.Select(x => new SlikaVM
                    {
                        KlijentId = x.KlijentId,
                        PutanjaDoSlike = x.PutanjaDoSlike,
                        Napomena = x.Napomena,
                        SlikaId = x.SlikaId
                    }).Where(x => x.KlijentId == klijentId)
                      .ToList();

                    ViewBag.klijentId = klijentId;

                    return PartialView("Index_Partial", slike);
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        // GET: Slika/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                    SlikaVM slika = context.Slika.Where(x => x.SlikaId == id).Select(x => new SlikaVM
                    {
                        KlijentId = x.KlijentId,
                        Napomena = x.Napomena,
                        PutanjaDoSlike = x.PutanjaDoSlike,
                        SlikaId = x.SlikaId

                    }).FirstOrDefault();

                    return PartialView("Details_Partial", slika);
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        // POST: Slika/Create
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file, string opis, int klijentId, int slikaId = 0)
        {
            try
            {
                    Slika slikaZaDodati;

                    if (slikaId != 0)
                    {
                        slikaZaDodati = context.Slika.Where(x => x.SlikaId == slikaId).FirstOrDefault();
                        slikaZaDodati.Napomena = opis != null ? opis : slikaZaDodati.Napomena;
                    }
                    else
                    {
                        slikaZaDodati = new Slika();
                        context.Slika.Add(slikaZaDodati);
                        slikaZaDodati.Napomena = opis;
                    }

                    if (file != null)
                    {
                        string klijent = context.Klijent.Where(x => x.KlijentId == klijentId).FirstOrDefault().Ime.Replace(' ', '_');

                        string slika = Path.GetFileName(file.FileName);
                        string ekstenzijaSlike = Path.GetExtension(file.FileName);

                        //generisanje unikatnog imena slici
                        slika = Guid.NewGuid().ToString() + ekstenzijaSlike;

                        System.IO.Directory.CreateDirectory(Path.Combine(Server.MapPath("~/Images/"), klijent.ToString()));
                        string path = Path.Combine(Server.MapPath("~/Images/" + klijent + "/"), slika);

                        WebImage img = new WebImage(file.InputStream);
                        if (img.Width > 400 || img.Height > 400)
                            img.Resize(350, 350);
                        img.Save(path);

                        slikaZaDodati.PutanjaDoSlike = "/Images/" + klijent.ToString() + "/" + slika;
                        slikaZaDodati.KlijentId = klijentId;
                    }

                    context.SaveChanges();

                    return Redirect("/Klijent/Details/" + klijentId);
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        // POST: Slika/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, int klijentId)
        {
            try
            {
                    Slika slika = context.Slika.Where(x => x.SlikaId == id).FirstOrDefault();
                    string fullPath = Request.MapPath(slika.PutanjaDoSlike);
                    System.IO.File.Delete(fullPath);

                    context.Slika.Remove(slika);
                    context.SaveChanges();
                    return RedirectToAction("Index", new { klijentId = klijentId });
            }
            catch (Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }
    }
}

SupportAplikacija/Views/Klijent/Create.cshtml
@model DAL.ViewModel.KlijentCreateVM

@{
    ViewBag.Title = "Dodaj Klijenta";

    //error
    string error = (string)ViewBag.error;
}

@*div u kojem se ispisuju error poruke*@
<div id="errorMessages">
</div>

@if (error != null)
{
    <div class='alert alert-danger col-md-4 col-sm-4 offset-4'>
        <strong>Error!</strong>@error.ToString()
    </div>
}

    @*ajax forma za dodavanje i editovanje klijenta*@
    @using (Ajax.BeginForm("Create", "Klijent", new AjaxOptions { HttpMethod = "POST", OnSuccess = "response(data, status, xhr)" }))
    {
        @Html.AntiForgeryToken()

        <div class="form">
            <div class="form-horizontal container-style" style="padding:5%;">
                @Html.ValidationSummary(true)

                @Html.HiddenFor(model => model.KlijentId)

                <div class="form-group">
                    <label for="@Model.Ime"><i style="color:red;" title="Ime je obavezno polje">*Ime Klijenta</i></label>
                    @Html.TextBoxFor(model => model.Ime, new { @class = "form-control col-md-12" })
                </div>
                <div class="form-group">
                    <label for="@Model.Alias">Alias</label>
                    @Html.TextBoxFor(model => model.Alias, new { @class = "form-control col-md-12" })
                </div>
                <div class="form-group">
                    <label for="@Model.Adresa"><i style="color:red;" title="Adresa je obavezno polje">*Adresa</i></label>
                    @Html.TextBoxFor(model => model.Adresa, new { @class = "form-control col-md-12" })
                </div>
                <div class="form-group">
                    <label for="@Model.GradId"><i style="color:red;" title="Grad je obavezno polje">*Grad</i></label>
                    <div class="row" style="margin:0;">
                        <select name="GradId" id="GradId" class="form-control col-md-4 mr-md-4 mb-2 mb-sm-0">
                            <option @(Model.GradId == 0 ? "selected" : "") value="">Odaberite grad</option>
                            @foreach (var item in Model.Gradovi)
                            {
                                <option @(Model.GradId.ToString().Equals(item.Value) ? "selected" : "") value="@item.Value">@item.Text</option>
                            }
                        </select>
                        <a href="" data-toggle="modal" data-target="#createGradModal" class="btn createBtn col-md-2 mb-2 mb-sm-0" title="Dodaj Grad"><i class="fa fa-plus" aria-hidden="true" style="margin:0;"></i></a>
                    </div>
                </div>
                <div class="form-group">
                    <label for="@Model.Telefon"><i style="color:red;" title="Telefon je obavezno polje">*Telefon</i></label>
                    @Html.TextBoxFor(model => model.Telefon, new { @class = "form-control col-md-12" })
                </div>
                <div class="form-group">
                    <label for="@Model.Napomena">Napomena</label>
                    @Html.TextAreaFor(model => model.Napomena, new { @class = "form-control col-md-12 mb-2 mb-sm-0" })
                </div>

                <button type="submit" class="btn btn-info form-control col-md-3 col-sm-6 col-xs-12">@(Model.KlijentId == 0 ? "Dodaj" : "Izmjeni")</button>
            </div>
        </div>
    }

    <!-- Modal -->
    <div class="modal fade" id="createGradModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.Action("CreateGrad")
                </div>
            </div>
        </div>
    </div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

    @*skripta za handlanje responsa ajax forme*@
    <script>
        function response(data, status, xhr) {

            var string = data + '';
            var stringSplit = string.split(',');

            $("#errorMessages").empty();

            if (!xhr.getResponseHeader('X-Error')) {
                swal({
                    type: 'success',
                    title: 'Klijent @(Model.KlijentId != 0?"izmjenjen":"dodan")',
                    showConfirmButton: true
                }).then(function () {
                    window.location.href = '/Klijent/@(Model.KlijentId != 0?"Details/" + Model.KlijentId:"Index")'
                });
            } else {
                for (var i = 0; i < stringSplit.length; i++) {
                    $("#errorMessages").append("<div class='alert alert-danger error mb-2'><strong>Error!</strong> " + stringSplit[i] + "</div>");
                }
            }
        }

    </script>

SupportAplikacija/Views/Klijent/CreateGrad_Partial.cshtml
@model DAL.ViewModel.GradCreateVM

@*div u kojem se ispisuju error poruke*@
<div id="errorMessagesGrad">
</div>

@using (Ajax.BeginForm("CreateGrad", "Klijent", new AjaxOptions { HttpMethod = "POST", OnSuccess = "responseGrad(data, status, xhr)" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        <div class="form-group">
            <label for="Naziv" class="col-form-label col-md-6">Naziv Grada:</label>
            <div class="col-md-10">
                <input type="text" id="Naziv" name="Naziv" class="form-control" value=" " />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<script>
        function responseGrad(data, status, xhr) {

            var string = data + '';
            var stringSplit = string.split(',');

            $("#errorMessagesGrad").empty();

            if (!xhr.getResponseHeader('X-Error')) {
                swal({
                    type: 'success',
                    title: 'Grad dodan!',
                    showConfirmButton: true
                }).then(function () {
                    $('#createGradModal').modal('toggle');
                    $('body').removeClass('modal-open');
                    $('.modal-backdrop').remove();

                    $('#GradId').append($('<option/>', {
                        value: data["GradId"],
                        text: data["Naziv"],
                        selected:true
                    }));
                });
            } else {
                for (var i = 0; i < stringSplit.length; i++) {
                    $("#errorMessagesGrad").append("<div class='alert alert-danger col-md-12 col-sm-12 offset-12'><strong>Error!</strong> " + stringSplit[i] + "</div>");
                }
            }
        }
</script>

SupportAplikacija/Views/Klijent/Details.cshtml
@model DAL.ViewModel.KlijentVM

@{
    ViewBag.Title = "Detalji";
}

<div id="detailsCard" class="card offset-4" style="box-shadow: 0 0 10px rgba(0,0,0,0.2);">
    <h1 class="card-header" style="text-align:center;background-color: #334; color:white;">@(Model.Ime)</h1>
    <div class="card-block" style="margin:2% 2% 0 0;">
        <a class="btn editBtn pull-right" href='#' title="Izbriši" style="font-size:15px;" onclick="deleteKlijent(@Model.KlijentId)"><i class="fa fa-trash fa-wa" style="color:#696666;"></i></a>
        <a class="btn editBtn pull-right" href='@Url.Action("Create", "Klijent", new {id = Model.KlijentId})' title="Uredi" style="font-size:15px;"><i class="fa fa-pencil fa-wa" style="color:#696666;"></i></a>
    </div>
    <div class="card-block card-body text-center">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <td class="align-content-right" width="50%"><strong>Grad:</strong></td>
                    <td class="align-content-left" width="50%">@Html.DisplayFor(x => x.Grad)</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>Datum dodavanja:</strong></td>
                    <td class="align-content-left">@Model.DatumDodavanja.ToString("dd/MM/yyyy HH:mm")</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>Datum uređivanja:</strong></td>
                    <td class="align-content-left">@Model.DatumUredjivanja.ToString("dd/MM/yyyy HH:mm")</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>Adresa:</strong></td>
                    <td class="align-content-left">@Html.DisplayFor(x => x.Adresa)</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>Telefon:</strong></td>
                    <td class="align-content-left">@Html.DisplayFor(x => x.Telefon)</td>
                </tr>
                <tr>
                    <td class="align-content-right"><strong>Napomena:</strong></td>
                    <td class="align-content-left">@Html.DisplayFor(x => x.Napomena)</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="card-block">
        <div class="row" style="margin:0;">
            @Ajax.ActionLink("Intervencije", "Index", "Intervencija", new { klijentId = Model.KlijentId }, new AjaxOptions { UpdateTargetId = "ajaxDiv" }, new { @class = "col-md-3 col-sm-12 filterBtn" })
            @Ajax.ActionLink("Kase", "Index", "Kasa", new { klijentId = Model.KlijentId }, new AjaxOptions { UpdateTargetId = "ajaxDiv" }, new { @class = "col-md-3 col-sm-12 filterBtn" })
            @Ajax.ActionLink("Računari", "Index", "Racunar", new { klijentId = Model.KlijentId }, new AjaxOptions { UpdateTargetId = "ajaxDiv" }, new { @class = "col-md-3 col-sm-12 filterBtn" })
            @Ajax.ActionLink("Slike", "Index", "Slika", new { klijentId = Model.KlijentId }, new AjaxOptions { UpdateTargetId = "ajaxDiv" }, new { @class = "col-md-3 col-sm-12 filterBtn" })
        </div>
    </div>
    <div class="card-block card-body" style="background-color: rgba(0,0,0,.03);">
        <div id="ajaxDiv" class="col-md-12"></div>
    </div>
</div>

<script type="text/javascript">
    function deleteKlijent(klijentId) {
        swal({
            title: 'Dali ste sigurni?',
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Da, obriši!',
            cancelButtonText: 'Ne',
        }).then((result) => {
            if (result.value) {
                $.ajax({
            type: "POST",
            url: "/Klijent/Delete?id=" + klijentId,
        success: (location.href = "/Klijent/Index"),
        dataType: "json"
    });
    }
    })
    }
</script>

SupportAplikacija/Views/Klijent/Index.cshtml
@model IEnumerable<DAL.ViewModel.KlijentVM>

@{
    ViewBag.Title = "Klijenti";
    var numberOfPages = (int)ViewBag.numberOfPages;
    var currentPage = (int)ViewBag.currentPage;

    //filteri
    var searchInput = (string)ViewBag.searchInput;
    var dateFrom = (string)ViewBag.dateFrom;
    var dateTo = (string)ViewBag.dateTo;
}


<div class="container-style">
    @*filteri za pretragu klijenata i dugme za dodavanje novog klijenta*@
    <div id="filterWrapper">
        <form action="/Klijent/Index" method="get" class="form-inline">
            <a href="" data-toggle="modal" data-target="#infoModal" class="mr-1" title="Informacije o pretrazi..."><i class="fa fa-info-circle icon-size" aria-hidden="true" style="color:#168ece"></i></a>
            <input id="searchInput" type="text" name="searchInput" class="form-control mr-1" placeholder="Pretraga..." value="@searchInput" />

            <span class="col-xs-1" for="dateFrom" style="margin-right:1%;"><strong>Od:</strong></span>
            <input id="dateFrom" type="date" class="form-control mr-1" name="dateFrom" value="@dateFrom" />

            <span class="col-xs-1" for="dateTo" style="margin-right:1%;"><strong>Do:</strong></span>
            <input id="dateTo" type="date" class="form-control mr-2" name="dateTo" value="@dateTo" placeholder="Do" />

            <button id="searchBtn" type="submit" class="btn createBtn form-control mr-2 pointer">Pretraži&nbsp;<i class="fa fa-search fa-fw"></i></button>

            <a id="clearFilterBtn" href="/Klijent/Index" class="btn btn-danger form-control mr-2 pointer">Očisti filtere&nbsp;<i class="fa fa-times fa-fw"></i></a>
        </form>
    </div>

    <div style="margin-bottom:2%;">
        @Html.ActionLink("Dodaj Klijenta", "Create", null, new { @class = "btn btn-info" })
    </div>
    @*tabela sa listom klijenata*@
    @if (Model.Count() > 0)
    {
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col" style="width:14.28%;">Grad</th>
                    <th scope="col" style="width:14.28%;">Ime Klijenta</th>
                    <th scope="col" style="width:14.28%;">Alias</th>
                    <th scope="col" style="width:14.28%;">Telefon</th>
                    <th scope="col" style="width:14.28%;">Adresa</th>
                    <th scope="col" style="width:14.28%;">Dodan</th>
                    <th scope="col" style="width:14.28%;">Izmjenjen</th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr style="background: rgba(164, 209, 234, 0.1);" onclick="location.href = '@Url.Action("Details", "Klijent", new {id = item.KlijentId})'">
                    <td scope="row" data-label="Grad">@Html.DisplayFor(modelItem => item.Grad)</td>
                    <td data-label="Ime Klijenta">@Html.DisplayFor(modelItem => item.Ime)</td>
                    <td data-label="Alias">@Html.DisplayFor(modelItem => item.Alias)</td>
                    <td data-label="Telefon">@Html.DisplayFor(modelItem => item.Telefon)</td>
                    <td data-label="Adresa">@Html.DisplayFor(modelItem => item.Adresa)</td>
                    <td data-label="Dodan">@item.DatumDodavanja.ToString("dd/MM/yyyy HH:mm")</td>
                    <td data-label="Izmjenjen">@item.DatumUredjivanja.ToString("dd/MM/yyyy HH:mm")</td>
                </tr>
            }
        </table>
    }
    else
    {
        <div class="alert" style="text-align:center; background-color:rgba(175,175,175,0.1);">
            <h5>Nije pronađen nijedan klijent</h5>
        </div>
    }

    @*paginacija*@
    @if (numberOfPages > 1)
    {
        <div class="container">
            <ul class="pagination pagging-alignment">
                <li class="page-item  @(currentPage == 0?"disabled":"") "><a class="page-link" href="/Klijent/Index?currentPage=@(currentPage-1)">Prethodni</a></li>

                @for (int i = 0; i < numberOfPages; i++)
                {
                    <li class="page-item @(currentPage == i?" active":"")"><a class="page-link" href="/Klijent/Index?currentPage=@i">@(i + 1)</a></li>
                }

                <li class="page-item @(currentPage == numberOfPages-1?"disabled":"")"><a class="page-link" href="/Klijent/Index?currentPage=@(currentPage+1)">Sljedeći</a></li>
            </ul>
        </div>
    }
</div>



<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                Pretraga se može vršiti po sljedećim parametrima:
                <ul>
                    <li>Ime Klijenta</li>
                    <li>Grad</li>
                    <li>Alias</li>
                    <li>Telefon</li>
                    <li>Adresa</li>
                </ul>
            </div>
        </div>
    </div>
</div>