SupportAplikacija/Controllers/KorisnikController.cs
using DAL;
using DAL.Models;
using DAL.ViewModel;
using SupportAplikacija.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SupportAplikacija.Controllers
{
    [Authorize]
    public class KorisnikController : Controller
    {
        SupportContext context = new SupportContext();

        // GET: /Korisnik/
        public ActionResult Index()
        {
            try
            {
                    int idKorisnika = HttpContext.Session["korisnik"] != null ? ((Korisnik)HttpContext.Session["korisnik"]).KorisnikId :Int32.Parse(Request.Cookies["korisnik"]["id"]);
                    KorisnikVM korisnik = context.Korisnik.Where(x => x.KorisnikId == idKorisnika)
                                                          .Select(x => new KorisnikVM
                                                            {
                                                                KorisnikId = x.KorisnikId,
                                                                Ime = x.Ime,
                                                                Prezime = x.Prezime,
                                                                Email = x.Email,
                                                                Password = x.Password,
                                                                Telefon = x.Telefon,
                                                                UserName = x.UserName
                                                            }).FirstOrDefault();

                    Session["Selected"] = "KorisnikIndex";
                    return View(korisnik);
            }
            catch(Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        //
        // GET: /Korisnik/Create
        public ActionResult Create()
        {
            try
            {
                    int idKorisnika = HttpContext.Session["korisnik"] != null ? ((Korisnik)HttpContext.Session["korisnik"]).KorisnikId : Int32.Parse(Request.Cookies["korisnik"]["id"]);
                    KorisnikCreateVM korisnik = context.Korisnik.Where(x => x.KorisnikId == idKorisnika).Select(x => new KorisnikCreateVM
                    {
                        KorisnikId = x.KorisnikId,
                        Ime = x.Ime,
                        Prezime = x.Prezime,
                        Email = x.Email,
                        Telefon = x.Telefon,
                        Password = x.Password,
                        UserName = x.UserName
                    }).FirstOrDefault();

                    ViewBag.allErrors = null;

                    return PartialView("Create",korisnik);
            }
            catch(Exception exception){
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }

        //
        // POST: /Korisnik/Create
        [HttpPost]
        public ActionResult Create(KorisnikCreateVM korisnikVM)
        {
            try
            {
                Korisnik korisnik = context.Korisnik.Where(x => x.KorisnikId == korisnikVM.KorisnikId).FirstOrDefault();
                List<string> allErrors = new List<string>();

                #region provjera ispravnosti unesenih podataka
                if (!ModelState.IsValid)
                {
                    foreach (ModelState modelState in ViewData.ModelState.Values)
                    {
                        foreach (ModelError error in modelState.Errors)
                        {
                            allErrors.Add(error.ErrorMessage.ToString());
                        }
                    }

                    ViewBag.allErrors = allErrors;

                    return PartialView("Create",korisnikVM);
                }
                #endregion

                #region Provjera pasvorda
                if (korisnikVM.StariPassword != null)
                {
                    if (!korisnik.Password.Equals(Helpers.Hash(korisnikVM.StariPassword)) && korisnikVM.StariPassword != null)
                    {
                        allErrors.Add("Stari password je neispravan!");
                        ViewBag.allErrors = allErrors;

                        return PartialView("Create", korisnikVM);
                    }
                    else
                    {
                        korisnik.Password = Helpers.Hash(korisnikVM.Password);
                    }
                }
                else
                {
                    korisnik.Password = korisnik.Password;
                }
                #endregion

                korisnik.Ime = korisnikVM.Ime;
                korisnik.Prezime = korisnikVM.Prezime;
                korisnik.UserName = korisnikVM.UserName;
                korisnik.Telefon = korisnikVM.Telefon;
                korisnik.Email = korisnikVM.Email;

                context.SaveChanges();

                KorisnikVM korisnikView = new KorisnikVM();
                korisnikView.KorisnikId = korisnik.KorisnikId;
                korisnikView.Ime = korisnik.Ime;
                korisnikView.Prezime = korisnik.Prezime;
                korisnikView.Email = korisnik.Email;
                korisnikView.Telefon = korisnik.Telefon;
                korisnikView.UserName = korisnik.UserName;
                korisnikView.Password = korisnik.Password;

                return PartialView("Index_Partial", korisnikView);
            }
            catch(Exception exception)
            {
                ViewBag.fatalError = exception;

                return PartialView("ErrorPage");
            }
        }
    }
}

SupportAplikacija/Views/Korisnik/Create.cshtml
@model DAL.ViewModel.KorisnikCreateVM

@{
    var allErrors = (List<string>)ViewBag.allErrors;
}

<div id="errorMessages">
    @if (allErrors != null)
    {
        foreach (var item in allErrors)
        {
            <div class='alert alert-danger col-md-12 col-sm-12 offset-12'>
                <strong>Error!</strong>@item.ToString()
            </div>
        }
    }
    </div>
@using (Ajax.BeginForm("Create", "Korisnik", null, new AjaxOptions { UpdateTargetId = "userAjax", HttpMethod = "POST" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.KorisnikId)
    
    <table class="table table-user-information">
        <tbody>
            <tr>
                <td style="width:50%;" class="align-content-right">Ime:</td>
                <td style="width:50%;" class="align-content-left"><input class="form-control" type="text" name="Ime" value="@Html.DisplayFor(x => x.Ime)" /></td>
            </tr>
            <tr>
                <td style="width:50%;" class="align-content-right">Prezime:</td>
                <td style="width:50%;" class="align-content-left"><input class="form-control" type="text" name="Prezime" value="@Html.DisplayFor(x => x.Prezime)" /></td>
            </tr>
            <tr>
                <td style="width:50%;" class="align-content-right">Username:</td>
                <td style="width:50%;" class="align-content-left"><input class="form-control" type="text" name="UserName" value="@Html.DisplayFor(x => x.UserName)" /></td>
            </tr>
            <tr>
                <td style="width:50%;" class="align-content-right">Stari password:</td>
                <td style="width:50%;" class="align-content-left"><input class="form-control" type="password" name="StariPassword" value="" /></td>
            </tr>
            <tr>
                <td style="width:50%;" class="align-content-right">Novi password:</td>
                <td style="width:50%;" class="align-content-left"><input class="form-control" type="password" name="Password" value="" /></td>
            </tr>
            <tr>
                <td style="width:50%;" class="align-content-right">Email:</td>
                <td style="width:50%;" class="align-content-left"><input class="form-control" type="text" name="Email" value="@Html.DisplayFor(x => x.Email)"/> </td>
            </tr>
            <tr>
                <td style="width:50%;" class="align-content-right">Telefon:</td>
                <td style="width:50%;" class="align-content-left"><input class="form-control" type="tel" name="Telefon" value="@Html.DisplayFor(x => x.Telefon)" /></td>
            </tr>
        </tbody>
    </table>

    <input type="submit" value="Uredi" class="btn btn-info form-control col-md-3 col-sm-6 col-xs-12 pointer" />
}

SupportAplikacija/Views/Korisnik/Index.cshtml
@model DAL.ViewModel.KorisnikVM

@{
    ViewBag.Title = "Profil";
}

<div id="detailsCard" class="card offset-4" style="box-shadow:0 10px 10px rgba(0,0,0,0.1)">
    <h1 class="card-header" style="text-align:center;background-color: #334; color:white;">@(Model.Ime + " " + Model.Prezime)</h1>
    <div class="card-block card-body text-center">
        <div id="userAjax">
            @Html.Partial("Index_Partial", Model)
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

SupportAplikacija/Views/Korisnik/Index_Partial.cshtml
@model DAL.ViewModel.KorisnikVM

<div class="card-block" style="margin:2% 2% 0 0;">
    <a class="btn editBtn pull-right" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#userAjax" href='@Url.Action("Create", "Korisnik")' title="Uredi" style="font-size:15px;"><i class="fa fa-pencil fa-wa" style="color:#696666;"></i></a>
</div>
<table class="table table-user-information">
    <tbody>
        <tr>
            <td style="width:50%;" class="align-content-right">Username:</td>
            <td style="width:50%;" class="align-content-left"><input readonly class="form-control" type="text" name="name" value="@Html.DisplayFor(x => x.UserName)" /></td>
        </tr>
        <tr>
            <td style="width:50%;" class="align-content-right">Email:</td>
            <td style="width:50%;" class="align-content-left"><input readonly class="form-control" type="email" name="name" value="@Html.DisplayFor(x => x.Email)" /> </td>
        </tr>
        <tr>
            <td style="width:50%;" class="align-content-right">Telefon:</td>
            <td style="width:50%;" class="align-content-left"><input readonly class="form-control" type="tel" name="name" value="@Html.DisplayFor(x => x.Telefon)" /></td>
        </tr>
    </tbody>
</table>